# Numpy: Numerical Python library

In [2]:
import numpy as np

In [3]:
my_list=[1,2,3]

In [4]:
np.array(my_list) # cast my_list in np.array

array([1, 2, 3])

In [5]:
type(np.array(my_list))

numpy.ndarray

In [6]:
arr=np.array(my_list)

In [7]:
arr

array([1, 2, 3])

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,11) # from 0 and up to 11 (not including 11) evenly spaced by one

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
np.zeros(5) # 1X5 array filled with zeros

array([ 0.,  0.,  0.,  0.,  0.])

In [15]:
np.zeros((3,5)) # 3X5 array filled with zeros

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [16]:
np.ones(3)

array([ 1.,  1.,  1.])

In [17]:
np.ones((3,5))

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [18]:
np.linspace(0,11,10)

array([  0.        ,   1.22222222,   2.44444444,   3.66666667,
         4.88888889,   6.11111111,   7.33333333,   8.55555556,
         9.77777778,  11.        ])

In [19]:
np.linspace(0,11,11)

array([  0. ,   1.1,   2.2,   3.3,   4.4,   5.5,   6.6,   7.7,   8.8,
         9.9,  11. ])

In [20]:
np.arange(0,11,11)

array([0])

In [25]:
np.arange(0,11,3)

array([0, 3, 6, 9])

In [22]:
np.linspace(0,11,2)

array([  0.,  11.])

The difference between np.arange and np.linspace

- np.arange(start, stop, stepsize)

- np.linspace(start, stop, the number of elements)

(example)
- np.arange(0,11,2) => output: [0,2,4,6,8,10]
- np.linspace(0,11,2) => output: [0,11]

In [28]:
np.random.randint(0,10)
# first index is inclusive, second index is exclusive

0

In [29]:
np.random.randint(0,1000,(3,3))
# create 3X3 array filled with randint between 0 and 999

array([[305, 125, 877],
       [ 21, 486, 725],
       [413, 497, 819]])

In [33]:
np.random.seed(101)  # Fix the seed applied only in the same cell

np.random.randint(0,100,10)

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [36]:
np.random.randint(0,100,10) 

array([76, 95, 87,  0, 73,  8, 62, 36, 83, 99])

In [37]:
np.random.seed(101)
arr=np.random.randint(0,100,10)

In [38]:
arr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [40]:
arr.max()

95

In [41]:
arr.min()

9

In [42]:
arr.mean()

60.799999999999997

In [44]:
arr.argmax() # index location of max value

0

In [46]:
arr.argmin() # index location of min value

7

In [48]:
arr.reshape(2,5) #condition: 10=2X5

array([[95, 11, 81, 70, 63],
       [87, 75,  9, 77, 40]])

In [49]:
mat=np.arange(0,100).reshape(10,10)

In [50]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [51]:
mat[0,1] #indexing

1

In [53]:
mat[4,3] #indexing

43

In [56]:
mat[:,0] #first column

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [57]:
mat[5,:]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

In [59]:
mat[:,0:3]

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32],
       [40, 41, 42],
       [50, 51, 52],
       [60, 61, 62],
       [70, 71, 72],
       [80, 81, 82],
       [90, 91, 92]])

In [61]:
mat[0:3,0:3]

# Be careful that the last index will not be inlcuded

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [62]:
mat>46

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]], dtype=bool)

In [63]:
my_filter=mat>50

In [64]:
mat[my_filter]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [65]:
mat[mat>50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])