# Scikit-Learn for preprocessing

Two main things I am going to cover:

1) Scaling data

2) Splitting data into train set and test set

In [1]:
import numpy as np

In [2]:
from sklearn.preprocessing import MinMaxScaler

In [3]:
data=np.random.randint(0,100,(10,2))
data

array([[79,  3],
       [73, 64],
       [23, 90],
       [50,  1],
       [44, 66],
       [94,  9],
       [68, 84],
       [ 6, 38],
       [86, 60],
       [22, 23]])

In [4]:
scaler_model=MinMaxScaler()

In [5]:
type(scaler_model)

sklearn.preprocessing.data.MinMaxScaler

In [6]:
scaler_model.fit(data) # Fit the data beteen 0 and 1

C:\udemy\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int32 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


MinMaxScaler(copy=True, feature_range=(0, 1))

In [7]:
scaler_model.transform(data)

array([[ 0.82954545,  0.02247191],
       [ 0.76136364,  0.70786517],
       [ 0.19318182,  1.        ],
       [ 0.5       ,  0.        ],
       [ 0.43181818,  0.73033708],
       [ 1.        ,  0.08988764],
       [ 0.70454545,  0.93258427],
       [ 0.        ,  0.41573034],
       [ 0.90909091,  0.66292135],
       [ 0.18181818,  0.24719101]])

In [10]:
scaler_model.fit_transform(data)
# performs both two steps at once!

C:\udemy\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int32 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


array([[ 0.82954545,  0.02247191],
       [ 0.76136364,  0.70786517],
       [ 0.19318182,  1.        ],
       [ 0.5       ,  0.        ],
       [ 0.43181818,  0.73033708],
       [ 1.        ,  0.08988764],
       [ 0.70454545,  0.93258427],
       [ 0.        ,  0.41573034],
       [ 0.90909091,  0.66292135],
       [ 0.18181818,  0.24719101]])

In [12]:
import pandas as pd

In [13]:
my_data = np.random.randint(0,101,(50,4))
my_data

array([[ 76,  70,   8,  15],
       [  4,  12,  29,   6],
       [ 95,  38,  55,  74],
       [ 94,  35,  10,  12],
       [ 33,  15,  25,  48],
       [ 42,  17,  25,  62],
       [ 48,  43,   9,   7],
       [ 20,  63,  15,   6],
       [ 85,  49,  22,  47],
       [ 70,  24,  97,  20],
       [ 23,  62,  89,  27],
       [ 73,   3,  64,  89],
       [ 32,  54,  96, 100],
       [ 68,  95,  67,  85],
       [ 33,  16,  97,  18],
       [ 89,  73,   5,  31],
       [ 47,  13,  26,  47],
       [ 68,  14,  59,  92],
       [ 80,  82,  56,   0],
       [ 92,  42,  50,   4],
       [  2,  58,   6,  87],
       [ 52,  73,  90,  97],
       [ 59,  46,  14,  78],
       [ 35,  28,  93,  97],
       [ 97,  28,  28,  94],
       [ 60,  83,  93,  54],
       [ 37,  73,  66,   1],
       [ 44,  71,  24,  33],
       [  6,  48,  12,  38],
       [ 26,  81,  12,  44],
       [ 58,  76,  77,  14],
       [ 84,  92,  50,  52],
       [ 54,  81,  64,  79],
       [ 25,  73,  46,  76],
       [  9,  

In [15]:
df=pd.DataFrame(data=my_data)
df

0   1   2    3
0   76  70   8   15
1    4  12  29    6
2   95  38  55   74
3   94  35  10   12
4   33  15  25   48
5   42  17  25   62
6   48  43   9    7
7   20  63  15    6
8   85  49  22   47
9   70  24  97   20
10  23  62  89   27
11  73   3  64   89
12  32  54  96  100
13  68  95  67   85
14  33  16  97   18
15  89  73   5   31
16  47  13  26   47
17  68  14  59   92
18  80  82  56    0
19  92  42  50    4
20   2  58   6   87
21  52  73  90   97
22  59  46  14   78
23  35  28  93   97
24  97  28  28   94
25  60  83  93   54
26  37  73  66    1
27  44  71  24   33
28   6  48  12   38
29  26  81  12   44
30  58  76  77   14
31  84  92  50   52
32  54  81  64   79
33  25  73  46   76
34   9   8  84   80
35  30  71  51   31
36  55  28  66   12
37  73  36  21   33
38  29  34  89    9
39  23  10  94   63
40   2  30  66   11
41  57  99  73   59
42  41  37   3   84
43   5  82  35   47
44  93  13   2   45
45  64  69  65   55
46  88  42  38   67
47   3  53  50   79
48  81  79  77   12
49  47  82  89   88

In [16]:
df=pd.DataFrame(data=my_data, columns=['f1', 'f2', 'f3', 'label'])
df

f1  f2  f3  label
0   76  70   8     15
1    4  12  29      6
2   95  38  55     74
3   94  35  10     12
4   33  15  25     48
5   42  17  25     62
6   48  43   9      7
7   20  63  15      6
8   85  49  22     47
9   70  24  97     20
10  23  62  89     27
11  73   3  64     89
12  32  54  96    100
13  68  95  67     85
14  33  16  97     18
15  89  73   5     31
16  47  13  26     47
17  68  14  59     92
18  80  82  56      0
19  92  42  50      4
20   2  58   6     87
21  52  73  90     97
22  59  46  14     78
23  35  28  93     97
24  97  28  28     94
25  60  83  93     54
26  37  73  66      1
27  44  71  24     33
28   6  48  12     38
29  26  81  12     44
30  58  76  77     14
31  84  92  50     52
32  54  81  64     79
33  25  73  46     76
34   9   8  84     80
35  30  71  51     31
36  55  28  66     12
37  73  36  21     33
38  29  34  89      9
39  23  10  94     63
40   2  30  66     11
41  57  99  73     59
42  41  37   3     84
43   5  82  35     47
44  93  13   2     45
45  64  69  65     55
46  88  42  38     67
47   3  53  50     79
48  81  79  77     12
49  47  82  89     88

Now, I want to split the data  into test set and training set

In [17]:
x=df[['f1', 'f2', 'f3']]

In [18]:
y=df['label']

In [20]:
x

f1  f2  f3
0   76  70   8
1    4  12  29
2   95  38  55
3   94  35  10
4   33  15  25
5   42  17  25
6   48  43   9
7   20  63  15
8   85  49  22
9   70  24  97
10  23  62  89
11  73   3  64
12  32  54  96
13  68  95  67
14  33  16  97
15  89  73   5
16  47  13  26
17  68  14  59
18  80  82  56
19  92  42  50
20   2  58   6
21  52  73  90
22  59  46  14
23  35  28  93
24  97  28  28
25  60  83  93
26  37  73  66
27  44  71  24
28   6  48  12
29  26  81  12
30  58  76  77
31  84  92  50
32  54  81  64
33  25  73  46
34   9   8  84
35  30  71  51
36  55  28  66
37  73  36  21
38  29  34  89
39  23  10  94
40   2  30  66
41  57  99  73
42  41  37   3
43   5  82  35
44  93  13   2
45  64  69  65
46  88  42  38
47   3  53  50
48  81  79  77
49  47  82  89

In [21]:
y

0      15
1       6
2      74
3      12
4      48
5      62
6       7
7       6
8      47
9      20
10     27
11     89
12    100
13     85
14     18
15     31
16     47
17     92
18      0
19      4
20     87
21     97
22     78
23     97
24     94
25     54
26      1
27     33
28     38
29     44
30     14
31     52
32     79
33     76
34     80
35     31
36     12
37     33
38      9
39     63
40     11
41     59
42     84
43     47
44     45
45     55
46     67
47     79
48     12
49     88
Name: label, dtype: int32

In [22]:
from sklearn.model_selection import train_test_split

In [23]:
X_train, X_test, y_train, y_test = train_test_split(
...     x, y, test_size=0.3, random_state=101)

In [24]:
X_train.shape

(35, 3)

In [26]:
X_test.shape

(15, 3)