In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

1.2.1


In [3]:
hello=tf.constant("hello")

In [4]:
world=tf.constant("world")

In [5]:
type(hello) 

# NOT string object, but tensor object

tensorflow.python.framework.ops.Tensor

In [6]:
print(hello)

# IT doesn't work as we expected

Tensor("Const:0", shape=(), dtype=string)


In [11]:
with tf.Session() as sess:
    result=sess.run(hello+world)
    
print(result)

# This will print out the"hello"
# b means bytes literal

b'helloworld'


In [12]:
a=tf.constant(10)
b=tf.constant(20)

In [13]:
type(a)

tensorflow.python.framework.ops.Tensor

In [14]:
a+b

<tf.Tensor 'add_4:0' shape=() dtype=int32>

In [15]:
a+b

<tf.Tensor 'add_5:0' shape=() dtype=int32>

In [16]:
a+b

<tf.Tensor 'add_6:0' shape=() dtype=int32>

In [18]:
with tf.Session() as sess:
    result=sess.run(a+b)
print(result)

30


In [19]:
result

30

In [20]:
type(result)

numpy.int32

In [21]:
const=tf.constant(10)
fill_mat=tf.fill((4,4),10)

In [26]:
myzeros=tf.zeros((4,4))
myones=tf.ones((4,4))
myrandn=tf.random_normal((4,4), mean=0, stddev=1.0)

In [23]:
myrandu=tf.random_uniform((4,4), minval=0, maxval=1)

In [27]:
myzeros

<tf.Tensor 'zeros_2:0' shape=(4, 4) dtype=float32>

In [28]:
my_ops=[const, fill_mat, myzeros, myones, myrandn, myrandu]

In [29]:
my_ops

[<tf.Tensor 'Const_4:0' shape=() dtype=int32>,
 <tf.Tensor 'Fill:0' shape=(4, 4) dtype=int32>,
 <tf.Tensor 'zeros_2:0' shape=(4, 4) dtype=float32>,
 <tf.Tensor 'ones_2:0' shape=(4, 4) dtype=float32>,
 <tf.Tensor 'random_normal_2:0' shape=(4, 4) dtype=float32>,
 <tf.Tensor 'random_uniform:0' shape=(4, 4) dtype=float32>]

In [30]:
sess=tf.InteractiveSession()

In [31]:
for op in my_ops:
    print(sess.run(op))
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


[[-1.13516104  1.94710946 -0.25436699  0.09258914]
 [ 0.7745524  -0.77293307  0.453576    1.69245076]
 [ 0.67760611 -1.23734581 -0.02500268 -1.37421525]
 [ 0.0337634  -1.75417626 -0.21322361  0.8928619 ]]


[[ 0.64537358  0.32421803  0.69811058  0.58801436]
 [ 0.20736802  0.57893491  0.50285304  0.93100798]
 [ 0.55011296  0.86447167  0.96803474  0.98046279]
 [ 0.96221173  0.43900752  0.61633134  0.39235103]]




In [32]:
a=tf.constant([[1,2], [3,4]])

In [33]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [34]:
b=tf.constant([[10],[100]])

In [35]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [36]:
result=tf.matmul(a,b)

In [39]:
print(result)

Tensor("MatMul:0", shape=(2, 1), dtype=int32)


In [38]:
sess.run(result)

array([[210],
       [430]])

In [40]:
result

<tf.Tensor 'MatMul:0' shape=(2, 1) dtype=int32>

In [41]:
result.eval()

array([[210],
       [430]])